#!/bin/sh
### BEGIN INIT INFO
# Provides: dhcpv6-pd-refreshd
# Required-Start: $network $syslog $all
# Required-Stop:
# Should-Start:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start dhcpv6 upstream pd watchdog
# Description: Start dhcpv6 upstream pd watchdog
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
. /lib/init/vars.sh
. /lib/lsb/init-functions

export REFRESHD_CHECK_INTERFACE=eth0
export REFRESHD_PREFIX_LEN=56

do_start () {
  start-stop-daemon --start --exec /config/scripts/dhcpv6-pd-refreshd --background
}

do_stop () {
  start-stop-daemon --stop --exec /config/scripts/dhcpv6-pd-refreshd
}

echo "cmd: $1"

case "$1" in
  start)
    do_start
    ;;
  stop)
    do_stop
    ;;
  restart)
    do_stop
    sleep 3
    do_start
    ;;
  *)
    echo "Usage: dhcpv6-pd-refreshd [start|stop|restart]" >&2
    exit 3
    ;;
esac
